/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface CrlButton {
    /**
     * The variant of button to be used
     */
    variant: string;
  }
}
declare global {
  interface HTMLCrlButtonElement
    extends Components.CrlButton,
      HTMLStencilElement {}
  var HTMLCrlButtonElement: {
    prototype: HTMLCrlButtonElement;
    new (): HTMLCrlButtonElement;
  };
  interface HTMLElementTagNameMap {
    'crl-button': HTMLCrlButtonElement;
  }
}
declare namespace LocalJSX {
  interface CrlButton {
    /**
     * The variant of button to be used
     */
    variant?: string;
  }
  interface IntrinsicElements {
    'crl-button': CrlButton;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'crl-button': LocalJSX.CrlButton &
        JSXBase.HTMLAttributes<HTMLCrlButtonElement>;
    }
  }
}
