name: 🐞 Bug Report
description: Let us know if something is not working as expected!
labels: [bug, triage]
body:
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: 'A clear and concise description of what is currently happening.'
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      description: 'How is the expected behavior different from what is currently happening?'
      label: Expected Behaviour
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Information
      description: 'Add any other context or screenshots about the bug here.'
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/divetool/coral/blob/main/docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
