blank_issues_enabled: false
contact_links:
  - name: Read the community guidelines
    about: 'Please make sure you have read the submission guidelines before posting an issue'
    url: https://github.com/divetool/coral/blob/main/docs/CONTRIBUTING.md#-submitting-an-issue
  - name: Want to start a discussion?
    about: 'Want to start a thread to discuss an idea? Use the discussions feature provided by GitHub.'
    url: https://github.com/divetool/coral/discussions
  - name: Is your issue DiveTool related?
    about: 'If your issue is not related with this design system but rather related with DiveTool itself, please go to the DiveTool project and report it there.'
    url: https://github.com/divetool/divetool
