name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  ci:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    env:
      NX_BASE: origin/main
      NX_HEAD: HEAD
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7.12.2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm exec nx affected --target=build --parallel=3
      - run: pnpm exec nx affected --target=test --parallel=3
      - run: pnpm exec nx affected --target=e2e --parallel=3
